version: '3'

services:
  web:
    container_name: temploy-frontend
    build: ./
    command: npm start
    volumes:
      - ./:/var/www/node
      - /var/www/node/node_modules
    networks:
      - temployback_temploy
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=temploy.localhost

networks:
  temployback_temploy:
    external: True
